const data = {
  products: [
    {
      name: "Icoana1",
      slug: "icoana1",
      category: "Icoane",
      image: "/images/icoana1.jpg",
      description: "Icoana numarul 1",
      price: 350,
      size: "30cm x 30cm",
      inStock: true,
      banner: "/images/icoana1.jpg",
    },
    {
      name: "Icoana2",
      slug: "icoana2",
      category: "Icoane",
      image: "/images/icoana2.jpeg",
      description: "Icoana numarul 2",
      price: 290,
      size: "30cm x 25cm",
      inStock: true,
      banner: "/images/icoana2.jpg",
    },
    {
      name: "Icoana3",
      slug: "icoana3",
      category: "Icoane",
      image: "/images/icoana3.jpg",
      description: "Icoana numarul 3",
      price: 500,
      size: "50cm x 40cm",
      inStock: true,
      banner: "/images/icoana3.jpg",
    },
    {
      name: "Tabloul1",
      slug: "tabloul1",
      category: "Tablouri",
      image: "/images/Tabloul1.jpg",
      description: "Tabloul numarul 1",
      price: 499,
      size: "50cm x 30cm",
      inStock: true,
      banner: "/images/Tabloul1.jpg",
    },
    {
      name: "Tabloul2",
      slug: "tabloul2",
      category: "Tablouri",
      image: "/images/Tabloul2.jpeg",
      description: "Tabloul numarul 2",
      price: 120,
      size: "20cm x 20cm",
      inStock: true,
      banner: "/images/Tabloul2.jpg",
    },
    {
      name: "Tabloul3",
      slug: "tabloul3",
      category: "Tablouri",
      image: "/images/Tabloul3.jpg",
      description: "Tabloul numarul 3",
      price: 699,
      size: "50cm x 50cm",
      inStock: true,
      banner: "/images/Tabloul3.jpg",
    },
  ],
};

export default data;
